//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alat_za_praćenje_osobnih_financija
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlatZaPraćenjeOsobnihFinancijaEntities : DbContext
    {
        public AlatZaPraćenjeOsobnihFinancijaEntities()
            : base("name=AlatZaPraćenjeOsobnihFinancijaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Models.Kategorije_troskova> Kategorije_troskova { get; set; }
        public virtual DbSet<Models.Korisnici> Korisnicis { get; set; }
        public virtual DbSet<Models.Place> Places { get; set; }
        public virtual DbSet<Models.Troskovi> Troskovis { get; set; }
    }
}
