//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alat_za_praćenje_osobnih_financija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Troskovi
    {
        public int Id { get; set; }
        public int Id_Kategorija_troska { get; set; }
        public int Id_Korisnika { get; set; }
        public System.DateTime Datum { get; set; }
        public double Iznos { get; set; }
        public string Komentar { get; set; }
    
        public virtual Kategorije_troskova Kategorije_troskova { get; set; }
        public virtual Korisnici Korisnici { get; set; }
    }
}
